set nocompatible
" Pathogen
"execute pathogen#infect()
filetype off
set rtp+=~/.vim/bundle/vundle/
" Vundle bundles
call vundle#rc()
Bundle 'gmarik/vundle'
Bundle 'Valloric/YouCompleteMe'
Bundle 'tpope/vim-fugitive'

filetype on
syntax on

" Avoid vimdiff fg==bg confusion
highlight! link DiffText Todo

map <S-Enter> O<Esc>
map <CR> o<Esc>
set shiftwidth=4 softtabstop=4
set incsearch ignorecase hlsearch
" Press space to clear search highlighting and any message already displayed.
nnoremap <silent> <Space> :silent noh<Bar>echo<CR>
" Next Tab
nnoremap <silent> <C-Right> :tabnext<CR>
" Previous Tab
nnoremap <silent> <C-Left> :tabprevious<CR>
" New Tab
nnoremap <silent> <C-t> :tabnew<CR>
" When I close a tab, remove the buffer
set nohidden
" Real men use gcc
compiler gcc
" Cool tab completion stuff
set wildmenu
set wildmode=list:longest,full
" Who doesn't like autoindent?
set autoindent
" Spaces are better than a tab character
set expandtab
set smarttab
" Indent based on file type
filetype plugin indent on
" YCM configs
let g:ycm_autoclose_preview_window_after_completion=1
nnoremap <leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>
nnoremap <F5> :YcmForceCompileAndDiagnostics<CR>
let g:ycm_filetype_whitelist = { 'c': 1, 'cpp': 1, 'python':1 }
let g:ycm_confirm_extra_conf = 0
let g:ycm_min_num_of_chars_for_completion = 5
