# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi


export TERM=xterm-color
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'

# User specific aliases and functions
HISTCONTROL=ignoredups:erasedups:ignorespace
export HISTSIZE=10000
export HISTFILESIZE=100000
shopt -s histappend
# check and set LINE and COLUMNS after each command
shopt -s checkwinsize
# PROMPT_COMMAND="history -n; history -w; history -c; history -r; $PROMPT_COMMAND"
bind '"\e[A"':history-search-backward
bind '"\e[B"':history-search-forward

