# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi


export TERM=xterm-color
alias grep='grep -n --color=auto'

# User specific aliases and functions
HISTCONTROL=ignoredups:erasedups:ignorespace
shopt -s histappend
# check and set LINE and COLUMNS after each command
shopt -s checkwinsize
# PROMPT_COMMAND="history -n; history -w; history -c; history -r; $PROMPT_COMMAND"
export HISTSIZE=10000
export HISTFILESIZE=100000
bind '"\e[A"':history-search-backward
bind '"\e[B"':history-search-forward
bind '"\eOA"':history-search-backward
bind '"\eOB"':history-search-forward

